import {
  LoginEvent,
  RiskThresholdSettings,
  SecurityAlert,
  UserAccount,
} from './types';

export const INITIAL_THRESHOLDS: RiskThresholdSettings = {
  lowMax: 39,
  mediumMax: 69,
  highMin: 70,
  enableOtpOnMedium: true,
  strictVpnPolicy: false,
  maxFailedAttemptsLock: 5,
  alertEmailDistribution: 'secops-alerts@riskauth.internal',
  autoQuarantineThreshold: 85,
};

export const MOCK_USERS: UserAccount[] = [
  {
    id: 'usr_01',
    name: 'Elena Rostova',
    email: 'elena.rostova@enterprise.corp',
    role: 'Security Admin',
    status: 'Active',
    riskLevel: 'LOW',
    avgRiskScore: 14,
    lastLogin: '2 mins ago',
    trustedDevicesCount: 2,
    department: 'Information Security',
  },
  {
    id: 'usr_02',
    name: 'Marcus Vance',
    email: 'marcus.vance@enterprise.corp',
    role: 'DevOps Lead',
    status: 'Active',
    riskLevel: 'LOW',
    avgRiskScore: 18,
    lastLogin: '18 mins ago',
    trustedDevicesCount: 3,
    department: 'Cloud Infrastructure',
  },
  {
    id: 'usr_03',
    name: 'Sofia Morales',
    email: 'sofia.morales@enterprise.corp',
    role: 'Platform Engineer',
    status: 'Active',
    riskLevel: 'MEDIUM',
    avgRiskScore: 48,
    lastLogin: '1 hour ago',
    trustedDevicesCount: 1,
    department: 'Core Banking API',
  },
  {
    id: 'usr_04',
    name: 'Kaito Tanaka',
    email: 'kaito.tanaka@enterprise.corp',
    role: 'SOC Analyst',
    status: 'Active',
    riskLevel: 'LOW',
    avgRiskScore: 12,
    lastLogin: '3 hours ago',
    trustedDevicesCount: 2,
    department: 'Security Operations',
  },
  {
    id: 'usr_05',
    name: 'David Okafor',
    email: 'david.okafor@enterprise.corp',
    role: 'Finance Director',
    status: 'Under Review',
    riskLevel: 'HIGH',
    avgRiskScore: 84,
    lastLogin: '4 hours ago',
    trustedDevicesCount: 1,
    department: 'Treasury & Compliance',
  },
  {
    id: 'usr_06',
    name: 'Aria Stirling',
    email: 'aria.stirling@enterprise.corp',
    role: 'Product Manager',
    status: 'Active',
    riskLevel: 'LOW',
    avgRiskScore: 22,
    lastLogin: 'Yesterday',
    trustedDevicesCount: 2,
    department: 'Payments Suite',
  },
];

export const MOCK_LOGIN_EVENTS: LoginEvent[] = [
  {
    id: 'evt_1001',
    userEmail: 'david.okafor@enterprise.corp',
    userName: 'David Okafor',
    timestamp: '2026-09-28 10:48:12',
    ipAddress: '185.220.101.5',
    device: 'Unknown Linux x86_64',
    deviceStatus: 'unknown',
    location: 'Frankfurt, Germany',
    locationStatus: 'unusual',
    vpn: true,
    riskScore: 89,
    riskLevel: 'HIGH',
    decision: 'BLOCK',
    failedAttempts: 5,
    behaviour: 'suspicious',
    loginTimeStatus: 'unusual',
    riskFactors: ['Commercial Tor Exit Relay', '5 Failed Passwords', 'Impossible Velocity from Lagos'],
  },
  {
    id: 'evt_1002',
    userEmail: 'sofia.morales@enterprise.corp',
    userName: 'Sofia Morales',
    timestamp: '2026-09-28 09:32:44',
    ipAddress: '82.165.197.88',
    device: 'MacBook Air M2',
    deviceStatus: 'unknown',
    location: 'London, United Kingdom',
    locationStatus: 'unusual',
    vpn: false,
    riskScore: 54,
    riskLevel: 'MEDIUM',
    decision: 'OTP',
    failedAttempts: 3,
    behaviour: 'normal',
    loginTimeStatus: 'normal',
    riskFactors: ['Unregistered Device Fingerprint', '3 Consecutive Failed Attempts'],
  },
  {
    id: 'evt_1003',
    userEmail: 'elena.rostova@enterprise.corp',
    userName: 'Elena Rostova',
    timestamp: '2026-09-28 09:15:02',
    ipAddress: '192.168.1.104',
    device: 'ThinkPad X1 Carbon',
    deviceStatus: 'trusted',
    location: 'San Francisco, CA, USA',
    locationStatus: 'normal',
    vpn: false,
    riskScore: 12,
    riskLevel: 'LOW',
    decision: 'ALLOW',
    failedAttempts: 0,
    behaviour: 'normal',
    loginTimeStatus: 'normal',
    riskFactors: [],
  },
  {
    id: 'evt_1004',
    userEmail: 'marcus.vance@enterprise.corp',
    userName: 'Marcus Vance',
    timestamp: '2026-09-28 08:52:19',
    ipAddress: '24.18.99.112',
    device: 'MacBook Pro 16" (Corporate)',
    deviceStatus: 'trusted',
    location: 'Seattle, WA, USA',
    locationStatus: 'normal',
    vpn: false,
    riskScore: 15,
    riskLevel: 'LOW',
    decision: 'ALLOW',
    failedAttempts: 0,
    behaviour: 'normal',
    loginTimeStatus: 'normal',
    riskFactors: [],
  },
  {
    id: 'evt_1005',
    userEmail: 'external_contractor@partner.io',
    userName: 'Contractor Session',
    timestamp: '2026-09-28 07:44:31',
    ipAddress: '198.51.100.42',
    device: 'Dell Precision 5570',
    deviceStatus: 'unknown',
    location: 'Zurich, Switzerland',
    locationStatus: 'unusual',
    vpn: true,
    riskScore: 68,
    riskLevel: 'MEDIUM',
    decision: 'OTP',
    failedAttempts: 1,
    behaviour: 'normal',
    loginTimeStatus: 'normal',
    riskFactors: ['Corporate VPN ASN Mismatch', 'New Device Signature'],
  },
  {
    id: 'evt_1006',
    userEmail: 'kaito.tanaka@enterprise.corp',
    userName: 'Kaito Tanaka',
    timestamp: '2026-09-28 06:12:05',
    ipAddress: '133.242.18.90',
    device: 'MacBook Pro 14"',
    deviceStatus: 'trusted',
    location: 'Tokyo, Japan',
    locationStatus: 'normal',
    vpn: false,
    riskScore: 8,
    riskLevel: 'LOW',
    decision: 'ALLOW',
    failedAttempts: 0,
    behaviour: 'normal',
    loginTimeStatus: 'normal',
    riskFactors: [],
  },
  {
    id: 'evt_1007',
    userEmail: 'root_admin_attempt@enterprise.corp',
    userName: 'Unknown Intruder',
    timestamp: '2026-09-28 04:21:40',
    ipAddress: '91.240.118.23',
    device: 'Python-Requests/2.31 Automation',
    deviceStatus: 'unknown',
    location: 'Bucharest, Romania',
    locationStatus: 'unusual',
    vpn: true,
    riskScore: 96,
    riskLevel: 'HIGH',
    decision: 'BLOCK',
    failedAttempts: 12,
    behaviour: 'suspicious',
    loginTimeStatus: 'unusual',
    riskFactors: ['Automated Script Signature', 'Severe Brute-Force Spike', 'Anonymizer Relay Detected'],
  },
  {
    id: 'evt_1008',
    userEmail: 'aria.stirling@enterprise.corp',
    userName: 'Aria Stirling',
    timestamp: '2026-09-27 18:30:11',
    ipAddress: '73.189.44.15',
    device: 'iPad Pro iOS 17',
    deviceStatus: 'trusted',
    location: 'Austin, TX, USA',
    locationStatus: 'normal',
    vpn: false,
    riskScore: 19,
    riskLevel: 'LOW',
    decision: 'ALLOW',
    failedAttempts: 0,
    behaviour: 'normal',
    loginTimeStatus: 'normal',
    riskFactors: [],
  },
  {
    id: 'evt_1009',
    userEmail: 'david.okafor@enterprise.corp',
    userName: 'David Okafor',
    timestamp: '2026-09-27 15:10:00',
    ipAddress: '105.112.38.19',
    device: 'HP EliteBook 840',
    deviceStatus: 'trusted',
    location: 'Lagos, Nigeria',
    locationStatus: 'normal',
    vpn: false,
    riskScore: 24,
    riskLevel: 'LOW',
    decision: 'ALLOW',
    failedAttempts: 1,
    behaviour: 'normal',
    loginTimeStatus: 'normal',
    riskFactors: ['Single Failed Password Retry'],
  },
  {
    id: 'evt_1010',
    userEmail: 'service_account_ci@enterprise.corp',
    userName: 'CI Worker Node 03',
    timestamp: '2026-09-27 14:00:22',
    ipAddress: '35.198.20.14',
    device: 'Google Compute Engine Service Account',
    deviceStatus: 'trusted',
    location: 'Iowa, USA',
    locationStatus: 'normal',
    vpn: false,
    riskScore: 4,
    riskLevel: 'LOW',
    decision: 'ALLOW',
    failedAttempts: 0,
    behaviour: 'normal',
    loginTimeStatus: 'normal',
    riskFactors: [],
  },
];

export const MOCK_SECURITY_ALERTS: SecurityAlert[] = [
  {
    id: 'alt_901',
    title: 'Credential Stuffing Attack Intercepted',
    severity: 'critical',
    timestamp: '12 mins ago',
    userEmail: 'david.okafor@enterprise.corp',
    riskScore: 89,
    status: 'active',
    description: 'Login attempt blocked via automated Tor exit relay with 5 failed credential permutations.',
    signals: {
      device: 'Unknown Linux x86_64',
      ip: '185.220.101.5',
      location: 'Frankfurt, Germany',
      vpn: true,
      failedAttempts: 5,
    },
    recommendedAction: 'Enforce immediate credential reset and invalidate all active session tokens.',
  },
  {
    id: 'alt_902',
    title: 'Suspicious Geo-Velocity & Unknown Device',
    severity: 'medium',
    timestamp: '1 hour ago',
    userEmail: 'sofia.morales@enterprise.corp',
    riskScore: 54,
    status: 'investigating',
    description: 'User authenticated from London after previous session in San Francisco 3 hours prior. Step-up OTP triggered.',
    signals: {
      device: 'MacBook Air M2 (Unregistered)',
      ip: '82.165.197.88',
      location: 'London, UK',
      vpn: false,
      failedAttempts: 3,
    },
    recommendedAction: 'Verify employee travel itinerary with manager or await FIDO2 key verification.',
  },
  {
    id: 'alt_903',
    title: 'Automated Script Dictionary Attack',
    severity: 'critical',
    timestamp: '6 hours ago',
    userEmail: 'root_admin_attempt@enterprise.corp',
    riskScore: 96,
    status: 'resolved',
    description: 'Rapid sequential authentication probe originating from Romanian hosting provider ASN. Automatically blocked at edge.',
    signals: {
      device: 'Python-Requests / Headless',
      ip: '91.240.118.23',
      location: 'Bucharest, Romania',
      vpn: true,
      failedAttempts: 12,
    },
    recommendedAction: 'IP subnet added to temporary 48-hour firewall quarantine blacklist.',
  },
  {
    id: 'alt_904',
    title: 'High-Volume VPN Connection Spike',
    severity: 'low',
    timestamp: '12 hours ago',
    userEmail: 'external_contractor@partner.io',
    riskScore: 68,
    status: 'resolved',
    description: 'Contractor authenticated using NordVPN exit gateway. Step-up SMS OTP successfully verified.',
    signals: {
      device: 'Dell Precision 5570',
      ip: '198.51.100.42',
      location: 'Zurich, Switzerland',
      vpn: true,
      failedAttempts: 1,
    },
    recommendedAction: 'Remind contractor to route via dedicated enterprise WireGuard gateway.',
  },
];

export const MOCK_ACTIVITY_TIMELINE = [
  { time: '00:00', allowed: 120, otp: 8, blocked: 2 },
  { time: '02:00', allowed: 85, otp: 4, blocked: 1 },
  { time: '04:00', allowed: 62, otp: 7, blocked: 14 },
  { time: '06:00', allowed: 140, otp: 12, blocked: 3 },
  { time: '08:00', allowed: 480, otp: 34, blocked: 5 },
  { time: '10:00', allowed: 720, otp: 52, blocked: 9 },
  { time: '12:00', allowed: 640, otp: 41, blocked: 4 },
  { time: '14:00', allowed: 810, otp: 65, blocked: 12 },
  { time: '16:00', allowed: 790, otp: 48, blocked: 7 },
  { time: '18:00', allowed: 520, otp: 31, blocked: 8 },
  { time: '20:00', allowed: 310, otp: 19, blocked: 4 },
  { time: '22:00', allowed: 190, otp: 11, blocked: 6 },
];

export const MOCK_RISK_DISTRIBUTION = [
  { name: '0–19 (Minimal)', value: 3420, color: '#16A34A' },
  { name: '20–39 (Low)', value: 1140, color: '#65A30D' },
  { name: '40–59 (Medium-Low)', value: 410, color: '#EAB308' },
  { name: '60–69 (Medium-High)', value: 195, color: '#F97316' },
  { name: '70–89 (High)', value: 112, color: '#DC2626' },
  { name: '90–100 (Critical)', value: 48, color: '#991B1B' },
];

export const MOCK_SIGNAL_ANOMALY_BREAKDOWN = [
  { signal: 'Unrecognized Device', count: 480, percentage: 38 },
  { signal: 'Unusual Geolocation', count: 320, percentage: 25 },
  { signal: 'Commercial VPN / Proxy', count: 260, percentage: 20 },
  { signal: 'Password Retry Spike', count: 140, percentage: 11 },
  { signal: 'Biometric Discrepancy', count: 80, percentage: 6 },
];
